//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPS_ARCGIS_SCENARIO_MANAGER.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://services.arcgis.com/7DPiBDyCvtJlGoFZ/ArcGIS/rest/services/ASA_OilMap_Model" +
            "s/FeatureServer")]
        public string UrlFeatureService {
            get {
                return ((string)(this["UrlFeatureService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://services.arcgis.com/7DPiBDyCvtJlGoFZ/ArcGIS/rest/services/ASA_OilMap_Model" +
            "s/FeatureServer/0")]
        public string UrlLyrTrajectory {
            get {
                return ((string)(this["UrlLyrTrajectory"]));
            }
        }
    }
}
